apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: musicman-app-of-apps
  namespace: argocd
  labels:
    scope: music-man
spec:
  project: default
  source:
    repoURL: https://github.com/snothub/scaling-parakeet.git
    targetRevision: HEAD
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: music-man
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
