{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    component: database
spec:
  type: {{ .Values.database.service.type }}
  clusterIP: None  # Headless service for StatefulSet
  ports:
  - port: {{ .Values.database.service.port }}
    targetPort: {{ .Values.database.service.targetPort }}
    protocol: TCP
    name: postgresql
  selector:
    app: {{ .Release.Name }}
    component: database
{{- end }}
